class MosqueDataService {
  static List<Map<String, dynamic>> getSampleMosques() {
    return [
      {
        'id': '1',
        'name': 'Badshahi Mosque',
        'address': 'Walled City, Lahore, Punjab, Pakistan',
        'latitude': 31.5886,
        'longitude': 74.3093,
        'category': 'Historic Mosque',
        'prayerTimes': ['5:30 AM', '1:15 PM', '5:45 PM', '7:30 PM', '8:45 PM'],
        'phone': '+92-42-37222570',
        'description': 'Historic Mughal mosque commissioned by Emperor Aurangzeb in 1671. One of the largest mosques in the world.',
      },
      {
        'id': '2',
        'name': 'Faisal Mosque',
        'address': 'Islamabad, Islamabad Capital Territory, Pakistan',
        'latitude': 33.7297,
        'longitude': 73.0372,
        'category': 'National Mosque',
        'prayerTimes': ['5:25 AM', '1:10 PM', '5:40 PM', '7:25 PM', '8:40 PM'],
        'phone': '+92-51-9222570',
        'description': 'National mosque of Pakistan, designed by Turkish architect Vedat Dalokay. Modern architectural marvel.',
      },
      {
        'id': '3',
        'name': 'Data Darbar',
        'address': 'Data Gunj Bakhsh Road, Lahore, Punjab, Pakistan',
        'latitude': 31.5786,
        'longitude': 74.3242,
        'category': 'Shrine & Mosque',
        'prayerTimes': ['5:35 AM', '1:20 PM', '5:50 PM', '7:35 PM', '8:50 PM'],
        'phone': '+92-42-37360815',
        'description': 'Shrine of Ali Hujwiri (Data Ganj Bakhsh), one of the most important Sufi shrines in South Asia.',
      },
      {
        'id': '4',
        'name': 'Masjid-e-Tooba',
        'address': 'Defence Housing Authority, Karachi, Sindh, Pakistan',
        'latitude': 24.8159,
        'longitude': 67.0644,
        'category': 'Modern Mosque',
        'prayerTimes': ['5:30 AM', '1:15 PM', '5:45 PM', '7:30 PM', '8:45 PM'],
        'phone': '+92-21-35390815',
        'description': 'Single-dome mosque with beautiful architecture, also known as Gol Masjid (Round Mosque).',
      },
      {
        'id': '5',
        'name': 'Masjid Wazir Khan',
        'address': 'Walled City, Lahore, Punjab, Pakistan',
        'latitude': 31.5837,
        'longitude': 74.3160,
        'category': 'Historic Mosque',
        'prayerTimes': ['5:28 AM', '1:12 PM', '5:42 PM', '7:28 PM', '8:42 PM'],
        'phone': '+92-42-37222580',
        'description': 'Famous for its intricate tile work and frescoes, built during the reign of Shah Jahan.',
      },
      {
        'id': '6',
        'name': 'Shah Faisal Mosque',
        'address': 'University Road, Karachi, Sindh, Pakistan',
        'latitude': 24.9437,
        'longitude': 67.1297,
        'category': 'University Mosque',
        'prayerTimes': ['5:32 AM', '1:17 PM', '5:47 PM', '7:32 PM', '8:47 PM'],
        'phone': '+92-21-99261300',
        'description': 'Beautiful mosque serving the university community and surrounding areas.',
      },
      {
        'id': '7',
        'name': 'Jamia Masjid Sultania',
        'address': 'Gulberg, Lahore, Punjab, Pakistan',
        'latitude': 31.5204,
        'longitude': 74.3587,
        'category': 'Community Mosque',
        'prayerTimes': ['5:26 AM', '1:11 PM', '5:41 PM', '7:26 PM', '8:41 PM'],
        'phone': '+92-42-35714820',
        'description': 'Modern community mosque with excellent facilities for education and community events.',
      },
      {
        'id': '8',
        'name': 'Memon Masjid',
        'address': 'M.A. Jinnah Road, Karachi, Sindh, Pakistan',
        'latitude': 24.8615,
        'longitude': 67.0099,
        'category': 'Historic Mosque',
        'prayerTimes': ['5:29 AM', '1:14 PM', '5:44 PM', '7:29 PM', '8:44 PM'],
        'phone': '+92-21-32231450',
        'description': 'Historic mosque in the heart of Karachi, serving the Memon community and all Muslims.',
      },
    ];
  }
}